name: Daily News Sync
on:
  schedule:
    - cron: '0 22 * * *' # 每天台灣時間早上 6 點執行
  workflow_dispatch: # 允許手動執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run Crawler
        run: python crawler.py

      - name: Commit and Push
        run: |
          git config --global user.name "NewsBot"
          git config --global user.email "bot@github.com"
          git add news_data.json
          git commit -m "Update news data $(date)" || exit 0
          # 【最終手段】先拉取最新的變更，如果還是衝突就強制推上去
          git pull --rebase origin main
          git push -f origin main
